Update Debian package build configuration with new program name.

diff --git a/debian/readsb.postrm b/debian/readsb.postrm
--- a/debian/readsb.postrm
+++ b/debian/readsb.postrm
@@ -21,28 +21,29 @@ set -e
 
 case "$1" in
     purge)
-        rm -f /etc/default/dump1090-fa
+        rm -f /etc/default/readsb
         ;;
 
     remove)
         changed=false
-        if [ -e /etc/lighttpd/conf-enabled/89-dump1090-fa.conf ]
+        if [ -e /etc/lighttpd/conf-enabled/89-readsb.conf ]
         then
             echo "Disabling lighttpd integration.." >&2
-            lighty-disable-mod dump1090-fa || true
+            lighty-disable-mod readsb || true
             changed=true
         fi
 
-        if [ -e /etc/lighttpd/conf-enabled/88-dump1090-fa-statcache.conf ]
+        if [ -e /etc/lighttpd/conf-enabled/88-readsb-statcache.conf ]
         then
             echo "Disabling lighttpd integration (stat cache).." >&2
-            lighty-disable-mod dump1090-fa-statcache || true
+            lighty-disable-mod readsb-statcache || true
             changed=true
         fi
 
         if $changed
         then
             echo "Restarting lighttpd.." >&2
+            invoke-rc.d lighttpd force-reload || echo "Warning: lighttpd failed to reload configuration." >&2
             invoke-rc.d lighttpd restart || echo "Warning: lighttpd failed to restart." >&2
         fi
         ;;
